class Questions {
  List<String> questionslist = [
    'Bitte warten...',
    'Wer beantragt als erstes Hartz IV?',
    'Wer würde am ehesten aus einem Flugzeug springen?',
    'Wer wird als erster Millionär?',
    'Wen würdest du als Telefonjoker bei "Wer wird Millionär" anrufen?',
    'Wer wird als erstes berühmt?',
    'Wer würde als erstes zum Kannibalen werden und jemanden aufessen?',
    'Wer hat am meisten Klopapier gehamstert?',
    'Wer könnte am ehesten als Sternekoch arbeiten?',
    'Wer würde am ehesten beim Bachelor mitmachen?',
    'Und wer bei Prince Charming? (Gay Bachelor)',
    'Wer hätte am ehesten was mit dem eigenen Geschlecht?',
    'Wer hat als erstes einen Dreier?',
    'Wessen Kochkunst wird als erstes jemanden töten?',
    'Wer kommt als erstes ins Gefängnis ?',
    'Wer würde am ehesten etwas klauen?',
    'Wer hat als erstes Kinder?',
    'Wer wäre der/die beste Bundeskanzler/in?',
    'Wer würde am ehesten in einem Porno mitspielen?',
    'Wer würde am ehesten Sex für Geld anbieten?',
    'Wer würde beim Wettessen gewinnen?',
    'Wer würde am ehesten jemanden ermorden?',
    'Wer geht als erstes pleite?',
    'Wer würde die Hunger Games gewinnen?',
    'Wer würde eine Klobrille ablecken?',
    'Wer würde eine Vogelspinne streicheln?',
    'Wessen Fahrkünste sind so schlecht, dass er/sie durch die Führerschein Prüfung fallen würde?',
    'Wer würde am ehesten auswandern?',
    'Wer würde am ehesten einen Schönheitswettbewerb gewinnen?',
    'Wer würde am ehesten eine olympische Goldmedaille gewinnen?',
    'Wer könnte Chewbacca spielen (= wer ist am behaartesten)?',
    'Wer zieht als erstes wieder daheim ein?',
    'Wer würde als erstes ein Haustier verhungern lassen?',
    'Wer würde ein Rapbattle gewinnen?',
    'Wer würde am ehesten Fahrerflucht begehen?',
    'Wer würde am ehesten eine Bank überfallen?',
    'Wer würde am ehesten eine Schönheits-OP machen?',
    'Wer hat eine Schönheits-OP am meisten nötig? :P',
    'Wer würde am ehesten sein Haustier grillen?',
    'Wer hat am längsten auf seinen Schulabschluss gelernt?',
    'Wer verträgt am meisten Alkohol?',
    'Wer hat in seinem Leben am meisten Zertifikat/Urkunden erhalten?',
    'Wer hat am meisten Familie/Verwandtschaftsmitglieder?',
    'Wer hat schon am meisten von der Welt gesehen?',
    'Wer kann am besten auswendig lernen?',
    'Wer hat das größte Stilbewusstsein?',
    'Wer hat den größten Kleiderschrank?',
    'Wer ist am jüngsten von zu Hause ausgezogen?',
    'Wer hat das größte Selbstbewusstsein?',
    'Wer sammelt in seinem Leben die meisten Geschlechtskrankheiten?',
    'Wer lässt am öftesten das Zähne putzen ausfallen?',
    'Wer hatte bisher die meisten Orgasmen in seinem Leben?',
    'Wer findet sich selbst am allergeilsten?',
    'Wer verträgt am meisten?',
    'Wer ist die intelligenteste Person?',
    'Wer wird als erstes sterben?',
    'Wer bekommt das erste Kind?',
    'Wer ist, wenn er alt, ist am ehesten alleine mit 12 Katzen?',
    'Wer hat die beste Ausdauer?',
    'Wer hat in seinem Leben die längste Zeit am Stück nicht geduscht',
    'Wer kann die meisten Sprachen?',
    'Wer ist die extrovertierteste Person?',
    'Wer ist die introvertierteste Person?',
    'Wer hat die meisten Uhren?',
    'Wer hat die coolste Frisur?',
    'Wer ist die ängstlichste Person?',
    'Wer bringt die meisten Marshmallows auf einmal in den Mund?',
    'Wer könnte am besten in freier Wildnis überleben?',
    'Wer ist am besten erzogen?',
    'Wer ist am käuflichsten?',
    'Wer hat die längsten Zehennägel?',
    'Wer würde eher jemanden vor die Haustüre scheißen?',
    'Wer würde einen Affen aus dem Zoo mitnehmen?',
    'Wer würde stoned zur Polizeiwache fahren, um Hallo zu sagen?',
    'Wer würde falsch auf die Autobahn fahren?',
    'Wer würde in einem Ballettkostüme durch München laufen?',
    'Wer würde im Winter in einen See springen?',
    'Wer würde am ehesten einen Monat lang auf sein Handy verzichten?',
    'Wer würde sich eher eine Glatze rasieren?',
    'Wer würde ein Nutellabrot mit Käse überbacken?',
    'Wer würde am ehesten ein Wochenende lang nichts sagen?',
    'Wer würde am ehesten einen Fremden auf der Straße küssen?',
    'Wer würde seinen Insta-Account löschen?',
    'Wer würde den Badeanzug von Borat am Strand tragen?',
    'Wer würde sich beim Sex anpinkeln lassen?',
    'Wer wird als erster obdachlos werden?',
    'Wer würde am ehesten versehentlich getötet werden?',
    'Wer würde am ehesten sein Geschlecht ändern?',
    'Wer würde am ehesten seinen Partner betrügen?',
    'Wer würde am ehesten sein ganzes Geld in einem Casino ausgeben?',
    'Wer würde am ehesten im Winter barfuß laufen?',
    'Wer würde am ehesten mehr als ein/e Freund/in gleichzeitig haben?',
    'Wer würde am ehesten jemanden missbrauchen?',
    'Wer würde am ehesten einen Regenwurm essen?',
    'Wer würde am ehesten Fallschirmspringen?',
    'Wer würde am ehesten in Mühldorf am Stadtplatz ein Lied singen?',
    'Wer würde am ehesten Ein Kind adoptieren?',
    'Wer würde am ehesten den Mount Everest besteigen?',
    'Wer würde am ehesten in einem Raum voller Menschen laut furzen?',
    'Wer wird als erstes heiraten?',
    'Welcher Typ hatte am meisten Sexualpartner?',
    'Welche Frau hatte am meisten Sexualpartner?',
    'Wer würde am ehesten einen Marathon laufen können?',
    'Wer lag am öftesten im Krankenhaus?',
    'Wer braucht am längsten beim Scheißen?',
    'Wer ist am unzuverlässigsten?',
    'Wer hat den schlechtesten Orientierungssinn?',
    'Wer hatte als jüngstes das erste Mal?',
    'Wer hatte das älteste erste Mal?',
    'Wer hat in seinem Leben am öftesten von Alkohol gekotzt?',
    'Wer würde am längsten auf einer einsamen, unzivilisierten Insel überleben?',
    'Wer würde am längsten ohne Internet und moderne Technik auskommen?',
    'Wer würde am ehesten ein Aussteigerleben führen?',
    'Wer wird als erster im Knast landen?',
    'Wer hat die meisten Delikte begangen?',
    'Wer hat sich am öftesten in Gesellschaft anderer Menschen entblößt?',
    'Wer wird am ehesten ein genialer Wissenschaftler?',
    'Wer holt sich mal ein Sugarbabe/Gigolo?',
    'Wer ist der größte Umweltsünder?',
    'Wer hat das schlechteste Allgemeinwissen?',
    'Wenn alle an einer Stange über einem Abgrund hängen, wer hält am längsten durch?',
    'Wer ist am naivsten?',
    'Wer hat am jüngsten angefangen zu masturbieren?',
    'Wer singt am schrecklichsten?',
    'Wer würde es am ehesten schaffen, mit eigenen Händen ein Pferd zu töten?',
    'Wer ist am gelenkigsten?',
    ' Werkönnte am längsten fasten, wenn immer leckeres Essen bereitsteht?',
    'Wer kann die meisten Fremdsprachen?',
    'Wer würde am ehesten für die große Liebe auf einen anderen Kontinent ziehen?',
    'Wen haut es beim Bananaboot fahren als erstes runter?',
    'Wer würde am ehesten auf eine Verschwörungstheorie hereinfallen, oder selbst eine verbreiten? ',
    'Wer hat die geringste Sozialkompetenz?',
    'Wer würde am ehesten ganz offen mit seinen Eltern über sein Sexualleben sprechen?',
    'Wer ist der größte Eichhörnchenfan?',
    'Wer würde am ehesten bei einem Fußballspiel einen Flitzer machen?',
    'Wer ext am schnellsten Bier?',
    'Wer ist am größten?',
    'Wer ist der Sitcomexperte?',
    'Wer ist der beste Sprinter?',
    'Wer ist der schlechteste Arbeitnehmer?',
    'Wer kifft am meisten?',
    'Wer ist der krasseste Alkoholiker?',
    'Wer ist am häufigsten auf dem Klo?',
    'Wer braucht am längsten im Bad?',
    'Wer ist der weiblichste Mann?',
    'Wer würde am ehesten nackt durch München rennen?',
    'Wer ist die männlichste Frau?',
    'Wer ist die größte Prinzessin?',
    'Wer ist die kleinste Person?',
    'Wer hat die größte Filmesammlung?',
    'Wer hat die meisten Filme/Musik illegal heruntergeladen?',
    'Wer ist der größte Pornosuchti?',
    'Wer wird am längsten leben?',
    'Wer hat am meisten Gameboy gezockt?',
    'Wer hat am meisten Wii gespielt?',
    'Wer verlässt auch ohne Corona nie seine Wohnung?',
    'Wer würde das perfekte Dinner gewinnen?',
    'Wer kann nicht mal Toastbrot toasten?',
    'Wer wird der nächste Whistleblower?',
    'Wer würde bei Germanys Next Topmodel gewinnen?',
    'Wer würde DSDS gewinnen?',
    'Wer kann nicht mal ein Strichmännchen malen?',
    'Wer hat am ehesten eine Pornosammlung auf seinem PC gespeichert?',
    'Wer hat die meisten Handys in seinem Leben verloren?',
    'Wer wäre die beste Frau, wenn sich an Fasching alle Typen als Frau verkleiden?',
    'Wer wird am ehesten Professor werden?',
    'Wer wäre der beste Stripper?',
    'Wer wäre die beste Stripperin?',
    'Wer hätte bei einer Zombieapokalypse die besten Überlebenschancen?',
    'Wer wird mit 60 noch am besten Aussehen?',
    'Wer hat als erster Netflix durchgeschaut?',
    'Wer hat den asozialsten Musikgeschmack?',
    'Wer hat am häufigsten auf der Arbeit masturbiert?',
    'Wer ist der größte Pokémon Go Fan?',
    'Wer sollte nochmal den Deutschunterricht besuchen?',
    'Wer sollte nochmal den Matheunterricht besuchen?',
    'Wer wird mit 50 immer noch Single sein?',
    'Wer könnte mal im Dschungelcamp landen?',
    'Wer bräuchte seine Wohnung eigentlich gar nicht, weil er eh nie dort ist?',
    'Wer hat in seinem Leben am meisten Zeit mit Zocken verbracht?',
    'Wer hat in seinem Leben die meiste Zeit mit Serien / Filmen anschauen verbracht?',
    'Wer hat in seinem Leben die meiste Zeit mit vorm normalen Fernsehen vergammeln verbracht?',
    'Wer ist der größte Bücherwurm?',
    'Wer könnte versehentlich jemand anderen umbringen?',
    'Wer wäre am wahrscheinlichsten von seinen Eltern aus dem Haus geschmissen worden?',
    'Wer ist der größte Zigarettenschnorrer?',
    'Wer ist der größte Alkoholschnorrer?',
    'Wer ist der größte Essensschnorrer?',
    'Wer könnte den Darwin-Award (blödeste Art sich selbst umzubringen) gewinnen?',
    'Wer ist heimlich der größte GZSZ Fan?',
    'Wer hat die meisten Nacktbilder von sich selbst?',
    'Wer hat die meisten Nacktbilder von anderen auf dem Handy (oder anderen Orten)?',
    'Wer würde es am längsten ohne Sex aushalten?',
    'Wer lässt sich während der Corona-Quarantäne am meisten gehen? (du solltest vllt. Mal wieder duschen gehen)',
    'Wer ist am besten in Bierpong?',
    'Wer ist der/die sensibelste?',
    'Wer ist der/die krasseste Männer-/Weiberheld?',
    'Wer gibt monatlich am meisten Geld aus?',
    'Wer hat am meisten frei?',
    'Wer ist der größte Macho?',
    'Wer ist der netteste?',
    'Wer würde in einem IQ Test am schlechtesten abschneiden?',
    'Wer wird sich als nächstes von seinem Partner trennen?',
    'Wer ist das ultimative Faultier?',
    'Wer hat am ehesten Ähnlichkeit mit einem Kleinkind?',
    'Wer würde am ehesten für die Mafia arbeiten?',
    'Es ist dritter Weltkrieg: Wer von den Jungs würde am Schlachtfeld eher desertieren?',
    'Wer würde am ehesten sein Beatmungsgerät abgeben damit ein kleines Kind weiterleben kann?',
    'Wer würde bei einem großen Lotto Gewinn eine sehr hohe Summe spenden?',
    'Auf dem Mars werden Siedlungen gebaut: Wer würde als erster die Erde verlassen um dort ein neues Leben zu beginnen?',
    'Man erwischt den Partner beim betrügen: wer würde am ehesten durchdrehen und ihn/sie abstechen?',
    'Wir sind unheilbar krank: wer würde sich am ehesten einfrieren lassen, in der Hoffnung, dass es ist der Zukunft ein Heilmittel gibt?',
    'Wer fänd es gut wenn die mehrehe in Deutschland erlaubt wäre und würde davon Gebrauch machen?',
    'Wer würde am ehesten ein Kind adoptieren?',
    'Wer würde bei einer Zombieapokalypse als erstes draufgehen?',
    'Wer am ehesten sauer/enttäuscht wenn sich sein Kind als schwul/lesbisch/bi outet?',
    'Es gibt ein Medikament das ewiges Leben ermöglicht: wer würde es am ehesten nehmen?',
    'Es gibt eine App die anzeigt wann du sterbe wirst: wer würde diese am ehesten benutzen?',
    'Wer würde am ehesten eine Anzeige kriegen, weil er/sie die/den Ex stalkt?',
    'Wer würde die beste Influencerin abgeben?',
    'Wer schaut die abgedrehtesten Pornos?',
    'Wer wird am ehesten am Corona Virus sterben?',
    'Wer würde am ehesten 5+ Kinder bekommen?',
    'Wer wird am ehesten 100 oder älter werden?',
    'Wer würde am ehesten einer Sekte beitreten',
    'Wer hat die coolsten Eltern?',
    'Wer wird am ehesten alleine sterben?',
    'Wer würde am ehesten weiterhin mit seinem Partner zusammen bleiben obwohl dieser einen betrogen hat?',
    'Wer würde am ehesten einen Dieb beim entwischen helfen?',
    'Wer wacht trotz lautem Feueralarm nicht auf?',
    'Bei wem ist es am wahrscheinlichsten dass er ausversehen das Haus abfackelt?',
    'Wer würde nur des Geldes wegen heiraten?',
    'Wer hat den besten Style?',
    'Wer wird am ehesten einen Welt Rekord aufstellen?',
    'Wer kommt zu spät zu seiner eigenen Hochzeit?',
    'Wer heiratet am ehesten einen Drogenboss?',
    'Wer würde am ehesten seine eigene Reality-Show kriegen?',
    'Wer wird sich am ehesten weniger als eine Woche nach ihrer Hochzeit wieder scheiden lassen?',
    'Wer wird am ehesten mal Alkoholiker?',
    'Wer bekommt am wahrscheinlichsten einen Herzinfarkt, wenn er sich einen Horrorfilm ansieht?',
    'Wer würde höchstwahrscheinlich niemals ein Baby haben wollen?',
    'Wer ist die kreativste Person?',
    'Wer vergisst am ehesten den Geburtstag des liebsten?',
    'Wer verliert am ehesten Sachen wie Schlüssel/Geldbeutel etc..?',
    'Bei wem ist es am wahrscheinlichsten eine Woche ohne Dusche noch in die Arbeit zu gehen?',
    'Wer würde am ehesten mit seiner Professorin/ seinem Professor schlafen?',
    'Wer wäre der schlechteste Präsident/ die schlechteste Präsidentin?',
    'Wer würde am ehesten seinen Tod vortäuschen um neue anzufangen?',
    'Wer würde am ehesten weiterhin in einer toxischen Beziehung bleiben?',
    'Wer würde am ehesten bei einem sehr süffigen Abend in Vages einen unbekannten heiraten?',
    'Wer sperrt sich am wahrscheinlichsten selbst aus der Wohnung aus?',
    'Wer schnarcht am lautesten?',
    'Wer isst mit vollem Mund?',
    'Wer würde am ehesten bei einem ‚Ess Wettbewerb‘ gewinnen?',
    'Wer würde am ehesten überfahren werden weil er auf sein Handy schaut?',
    'Wer hat die meiste Handyzeit am Tag?',
    'Wer hat den längsten Penis?',
    'Wer hat die größten Füße?',
    'Wer ist am hässlichsten?',
    'Wer geht am öftesten essen?',
    'Wer gibt am meisten im Monat aus?',
    'Wer gibt am wenigsten im Monat aus?',
    'Wer hat den längsten Bart?',
    'Wer ist der Schwerste?',
    'Wer ist der leichteste?',
    'Wer ist am unordentlichsten?',
    'Wer riecht am besten?',
    'Wer raucht wie ein Schlot?',
    'Wer macht am meisten im Haushalt?',
    'Wer ist das größte Arschloch?',
    'Wer ist der größte Verfechter von Frauenrechten?',
    'Wer hat den besten Lebenslauf?',
    'Wer wird später am ehesten wie Charlie Sheen enden?',
    'Wer wird am ehesten später Taxifahrer?',
    'Wer wird der besoffenste Spieler heute Abend sein?',
    'Wer trinkt am wenigsten Alkohol?',
    'Wer trinkt nur, um dicht zu werden?',
    'Wer bekommt als erstes Corona?',
    'Wer wird der beste Taufpate/Taufpatin?',
    'Wer kann am besten mit Kindern umgehen?',
    'Wer wird der beste Vater/Mutter?',
    'Wer hat den höchsten Abschluss?',
    'Wer hat den besten Sex?',
    'Wer hat die meisten Stellungen ausprobiert?',
    'Wer hat am meisten Sexspielzeug?',
    'Wer lässt sich am liebsten von hinten nehmen?',
    'Wer trägt die teuersten Klamotten?',
    'Wer hat das teuerste Hobby?',
    'Wer ist der beste Arbeiter?',
    'Wer ist der schlechteste Arbeiter?',
    'Wer ist die Person mit den wenigstens Problemen?',
    'Wer ist die Person mit den meisten Problemen?',
    'Wer ist die glücklichste Person?',
    'Wer ist die traurigste Person?',
    'Wer geht am häufigsten für ein kleines Geschäft aufs Klo (am Tag)?',
    'Wer ist die nervigste Person?',
    'Wer ist die netteste Person?',
    'Wer hat am meisten Muskeln in Bezug auf das Eigengewicht?',
    'Wer hinterfragt am meisten?',
    'Wer masturbiert am meisten?',
    'Wer schläft am längsten?',
    'Wer braucht am wenigsten Schlaf?',
    'Wer würde am ehesten drogensüchtig werden (harte)?',
    'Wer würde am ehesten Obdachlose bei sich aufnehmen?',
    'Wer denkt am meisten nach?',
    'Wer denkt am wenigsten nach?',
    'Wer braucht am längsten, um sich fertig zu machen?',
    'Wer braucht am kürzesten, um sich fertig zu machen?',
    'Wer geht am öftesten zum Friseur?',
    'Wer unternimmt am meisten?',
    'Wer unternimmt am wenigsten?',
    'Wer die strukturierteste Person?',
    'Wer ist die verplanteste Person? (Keine Plan von irgendwas)',
    'Wer schreibt am schnellsten am Computer?',
    'Wer hat die schönste Handschrift?',
    'Wer schreibt am hässlichsten?',
    'Wer wüsste am wahrscheinlichsten nicht, wer der amerikanische Präsident ist?',
    'Wer wüsste am wahrscheinlichsten nicht, was eine Mascara ist?',
    'Wer gibt am meisten Geld für Urlaube aus?',
    'Wer gibt am meisten Geld für die neuste Technik aus?',
    'Wer gibt am meisten Geld für unsinnige Sachen aus?',
    'Wer redet am meisten?',
    'Wer redet am wenigsten über seine Probleme?',
    'Wer hat ehrlichsten in diesem Spiel abgestimmt?',
    'Wer lügt am meisten?',
    'Wer manipuliert am meisten?',
    'Wer sagt immer die Wahrheit?',
    'Wer hat den dunkelsten Charakter?',
    'Wer hat den fröhlichsten Charakter?',
    'Wer braucht am längsten für einen Orgasmus?',
    'Wer ist die durchschnittlichste Person?',
    'Wer würde am besten in die 60er Jahre passen?',
    'Wer ist am ehrgeizigsten?',
    'Wer ist der schlechteste Verlierer?',
    'Wer schummelt am meisten?',
  ];
}
